apiVersion: v1
kind: Secret
metadata:
  name: payment-secret
type: Opaque
stringData:
  db_host: "10.20.0.15"      # ← WRONG IP, no postgres here = crash!
  db_port: "5432"
  db_user: "admin"
  db_password: "secret123"
  db_name: "payments"
